### ISSUE TITLE
Doesn't recompile if including a gem that has assets

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/rails-assets#114]
## What happened?

* What were you attempting to do?
I was adding Rails Admin to my existing application.

* What did you expect to happen?
I expected the app to recompile the assets that are now included with the addition of Rails Admin.

* What was the actual behavior? Please provide log output, if possible.
The app reused the cache, and then my app crashed when I navigated to the Rails Admin dashboard once the built container started.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
`pack 0.20.0+git-66a4f32.build-2668`

* What buildpacks are you using? Please include versions.
```
paketo-buildpacks/ca-certificates 2.3.2
paketo-buildpacks/mri             0.2.4
paketo-buildpacks/bundler         0.1.8
paketo-buildpacks/bundle-install  0.2.3
paketo-buildpacks/node-engine     0.6.2
paketo-buildpacks/yarn            0.4.0
paketo-buildpacks/yarn-install    0.4.0
paketo-buildpacks/rails-assets    0.2.3
paketo-buildpacks/puma            0.0.60
```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
```
full: Pulling from paketobuildpacks/builder
Digest: sha256:7a005cbd13254a3b85c75526802212d41348e4521faab26f5d2adf3565f859bf
Status: Image is up to date for paketobuildpacks/builder:full
full-cnb: Pulling from paketobuildpacks/run
Digest: sha256:fac2ca83109101e0d1dd8c26707f5f58e05ccf52b2c42db95e25bda86b9887b2
Status: Image is up to date for paketobuildpacks/run:full-cnb
```

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

1. Build a basic Rails app.
2. `pack build` the app and see it succeed and run successfully.
3. Add the `rails_admin` gem to your Gemfile and install
4. Follow the directions to configure Rails Admin: https://github.com/sferik/rails_admin/wiki/Base-configuration
5. `pack build` the app and see it build successfully (assets should be reused from the cache)
6. Start the app and navigate to the admin page.
7. See the app crash with an error saying that it cannot find some required assets.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by fg-j** [comment]
Hey @ryanmoran, this issue has been open for a while. Are you still seeing this problem?
