### ISSUE TITLE
Assets are not precompiled after modifying files inside app/javascript

### ISSUE THREAD

**Issue by matiasgarcia** [paketo-buildpacks/rails-assets#38]
Configuration is the same as: https://github.com/paketo-buildpacks/rails-assets/issues/35

It seems that the layer is always reused if app/assets checksum matches, this can be seen on:
https://github.com/paketo-buildpacks/rails-assets/blob/main/build.go#L47-L51

The expected behaviour is that if we modify anything inside app/javascript the assets are recompiled again.

**Comment by genevieve** [comment]
Hey @matiasgarcia. Do you have documentation around the expected behavior regarding the `app/javascript` directory? From the rails asset pipeline docs, I don't see it referenced. https://guides.rubyonrails.org/asset_pipeline.html#how-to-use-the-asset-pipeline

**Comment by matiasgarcia** [comment]
Hi @genevieve docs should be in https://edgeguides.rubyonrails.org/webpacker.html. Both Webpacker and Sprockets live in a Rails 5/6 app.

**Comment by ryanmoran** [comment]
We should also include `lib/assets` and `vendor/assets` in the checksum so that we recompile if they include changes: https://edgeguides.rubyonrails.org/asset_pipeline.html#asset-organization.
