### ISSUE TITLE
Buildpack Feedback/Questions

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/rails-assets#4]
Hey @genevieve,
I'm a maintainer on the Paketo Ruby Buildpacks and was checking out your buildpack this afternoon and had a few questions. 

First of all, this buildpack looks awesome. I appreciate how you've used all of the usual patterns/packit tools we use in our other buildpacks. It fits in really well with the rest of the buildpacks in the group.

I had a few questions about the implementation so far!

1. In detection I noticed you pull in `yarn` as well as `node-engine` and I was wondering why it's needed? And whether its needed in every situation with asset compilation?

1. In build you set the `RAILS_ENV` variable. What's this for? When I run the integration tests / try to manually `pack build` as of now I see an error related to the production environment so I was wondering if this is related to this?

The error I see is `Missing secret_key_base for 'production' environment, set this string with rails credentials:edit`.

3. In build I see that you also set up a `railsLayer` but it doesn't get used with the precompile process. How do the compiled assets get put into this layer?

I think that's most of my questions for now. Let me know if there's a different place I should leave questions next time. Also feel free to reach out on Slack if you need any help!

**Comment by genevieve** [comment]
Hey Sophie! I'll answer these questions in separate comments as I do some investigation. For the second question:

> In build you set the RAILS_ENV variable. What's this for? When I run the integration tests / try to manually pack build as of now I see an error related to the production environment so I was wondering if this is related to this? The error I see is Missing secret_key_base for 'production' environment, set this string with rails credentials:edit.

The integration tests are passing for me so are you running pack build with a different application?

When we omit the `RAILS_ENV=production`, the integration test fails because it comes up in `development` environment and tries to run yarn:
```
=== CONT  TestIntegration/Integration/DefaultApp/when_building_a_default_rails_app/creates_a_working_OCI_image_with_compiled_rails_assets
    default_app_test.go:77:
        Timed out after 10.120s.
        Expected
        	docker container id: 9837abf52b9d005c03e31b19ad970d315ad8cd150feac85ed7ab83438efc23b6
        to be available.
        Container logs:
        Puma starting in single mode...
        * Version 4.3.7 (ruby 2.6.6-p146), codename: Mysterious Traveller
        * Min threads: 5, max threads: 5
        * Environment: development
        sh: 1: yarn: not found
        ========================================
          Your Yarn packages are out of date!
          Please run `yarn install --check-files` to update.
        ========================================
        To disable this check, please change `check_yarn_integrity`
        to `false` in your webpacker config file (config/webpacker.yml).
        ! Unable to load application: SystemExit: exit
Passed: 0 | Failed: 1 | Skipped: 0
```

**Comment by genevieve** [comment]
For your third question:

> In build I see that you also set up a railsLayer but it doesn't get used with the precompile process. How do the compiled assets get put into this layer?

I am working now on actually storing the directories with the compiled assets in the layer so they can be reused in this PR: https://github.com/genevieve/rails-assets/pull/5

If you have any feedback, it's still in progress but should address that question!

**Comment by sophiewigmore** [comment]
Hey @genevieve, I am running the integration tests exactly as they are in the master branch of the repo, with the `scripts/integration.sh` script. I'm not sure what's going wrong for me. I'll look into it though.

**Comment by sophiewigmore** [comment]
In reference to #5, using the code in the reuse-cache branch - it appears that when I rebuild the app with no asset changes, I see in the logs that it's reusing cached layers. However, when I look inside the container with `docker run -it --entrypoint=launcher railsapp /bin/bash`, and do an `ls` inside  `/layers/paketo-buildpacks_rails-assets/assets`, I do not see any assets. I'm not sure entirely how the rebuilds are working since the layer it's using for the rebuild is empty.

**Comment by genevieve** [comment]
For your first question:

> In detection I noticed you pull in yarn as well as node-engine and I was wondering why it's needed? And whether its needed in every situation with asset compilation?

I believe yarn is needed for rails assets precompilation. We can make it conditional on whether there's a `yarn.lock` file though so if there is no file, then we do not include yarn?

**Comment by genevieve** [comment]
For the assets reuse, it required a ton more directory and link changes than I had anticipated.

Here's the commit with the relevant changes: https://github.com/genevieve/rails-assets/pull/5/commits/73a837ff72d24d7f40c252e9f4ecb1de6df8c69f

**Comment by genevieve** [comment]
For your last question - the assets are now part of the `assets` layer for reuse on subsequent builds: https://github.com/genevieve/rails-assets/pull/5/files

**Comment by sophiewigmore** [comment]
> For your last question - the assets are now part of the `assets` layer for reuse on subsequent builds: https://github.com/genevieve/rails-assets/pull/5/files

These changes work great!

**Comment by sophiewigmore** [comment]
Possible next steps:
- are any other use cases that your buildpack should work with? /other test apps this could apply to? 
- does it work with other webservers?
- the tests take a while to run, can this be optimized in any way? What's the simplest possible app that this could work with

**Comment by bonzofenix** [comment]
@sophiewigmore when do you think this will be release with the ruby buildpack? thanks!

**Comment by sophiewigmore** [comment]
@bonzofenix we are going to add this to the Ruby buildpack once the integration testing is complete. Pull request #13 is open for this, so it shouldn't be too long. @ryanmoran is there anything else to add before we pull it into the language family?

**Comment by ryanmoran** [comment]
@sophiewigmore nope. It is feature complete at this point. There are some possible optimizations we might pursue in the future, but nothing worth blocking inclusion at this point.

**Comment by collimarco** [comment]
Have you solved the "missing secret_key_base" error? I have the same issue: https://github.com/paketo-buildpacks/rails-assets/issues/144
