### ISSUE TITLE
Integration tests  with `development` gems failing

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/rails-assets#49]
## What happened?

The integration tests that contain a `development` gem section in their `Gemfile` are failing (all tests that use the Rails 5.0 sample app) are failing with:

```
 Paketo Rails Assets Buildpack 1.2.3
          Executing build process
            Running 'bundle exec rails assets:precompile assets:clean'
        failed to execute bundle exec output:
        rails aborted!
        LoadError: cannot load such file -- uglifier
```
See [this workflow run](https://github.com/paketo-buildpacks/rails-assets/pull/46/checks?check_run_id=2139986452) for the full failure.

This is because the Bundle Install buildpack [v0.1.7](https://github.com/paketo-buildpacks/bundle-install/releases/tag/v0.1.7) no longer installs `development` gems per [this issue](https://github.com/paketo-buildpacks/bundle-install/issues/154). This issue did not become evident until the new Bundle Install release was added to the Ruby language family buildpack, and then the integration tests in the Rails Assets buildpack picked it up.

It seems that rails still needs access to the development gems in order to precompile assets, and without them, apps that have those development gems won't build.

Perhaps we should figure out a way to `bundle install` just the development gems to a temporary layer during the rails-assets buildpack build phase, so that they can be used for precompilation and then deleted in the final app image. 

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

pack 0.17.0

* What buildpacks are you using? Please include versions.

Ruby [v0.5.0](https://github.com/paketo-buildpacks/ruby/releases/tag/v0.5.0)

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

https://github.com/paketo-buildpacks/rails-assets/tree/main/integration/testdata/5.0

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
Resolved by https://github.com/paketo-buildpacks/bundle-install/pull/182
